### ISSUE TITLE
polyRoundExtrude cannot be used in difference

### ISSUE THREAD

**Issue by adam-trhon** [Irev-Dev/Round-Anything#12]
I cannot use polyRoundExtrude within difference(). I have OpenSCAD version 2019.05.

To reproduce it, here are some definitions first:

    use <polyround.scad>;

    base_outer_points = [
        [-10.5,  10,  1],
        [ 10.5,  10,  1],
        [ 10.5, -10,  1],
        [-10.5, -10,  1],
    ];
    base_outer_height = 6;

    base_inner_points = [
        [-9.5, -9, .5],
        [-9.5,  9, .5],
        [ 9.5,  9, .5],
        [ 9.5, -9, .5]
    ];  
    base_inner_height = 4;

When I append the following:

    difference() {
            polyRoundExtrude(base_outer_points, base_outer_height, 0.7, 0);
            translate([0, 0, -.1])
                polyRoundExtrude(base_inner_points, base_inner_height+.1, 0.7, 0);
    }

I get the following errors:

     ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e->incident_sface() != SFace_const_handle() File: /usr/include/CGAL/Nef_S2/SM_const_decorator.h Line: 330
     ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e->incident_sface() != SFace_const_handle() File: /usr/include/CGAL/Nef_S2/SM_const_decorator.h Line: 330

and the following output:

`![polyRoundExtrude-difference-result](https://user-images.githubusercontent.com/4278786/95026645-1f4c8600-0693-11eb-8f34-23310e1d576e.png)

**Comment by adam-trhon** [comment]
Just now I noticed the pull request #10 and a quick test revealed that it fixes this issue. Sorry for not checking before posting

**Comment by Irev-Dev** [comment]
All good @adam-trhon and thanks @nickcoutsos. I've asked for a couple of changes, but hope to get #10 merged soon.

**Comment by Irev-Dev** [comment]
#10 has been merged, going to close this issue. We can open it again if #10 didn't fix it entirely.
