### ISSUE TITLE
beamChain breaks on horizontal/vertical segments

### ISSUE THREAD

**Issue by lopisan** [Irev-Dev/Round-Anything#16]
Hi,
I've found that `beamChain` breaks on horizontal and vertical segments of polyline:

When `eps` is non-zero, it does work:
```
a=10;
eps=1e-6;
points=[[0, 0, 0], [0+eps, a, 0], [a, a+eps, 0]];
polygon(polyRound( beamChain(points, offset1=1, offset2=-1), 30));
```

but when `eps=0` it breaks (doesn't show anything and sometimes - not always throw a undef error):
```
a=10;
eps=0;
points=[[0, 0, 0], [0+eps, a, 0], [a, a+eps, 0]];
polygon(polyRound( beamChain(points, offset1=1, offset2=-1), 30));
```

PS: Thanks for the great library I'm starting with OpenSCAD and I like polyRound very much.

**Comment by Irev-Dev** [comment]
Hey @lopisan,
Thanks for reporting this bug.
Just wanted to let you know I'm busy the weekend, hopefully, I'll get to this early next week.

There's some documentation updates I need to do for beam chain anyway #11, so good extra prompt to get to it.

Glad you like the library 🤗

**Comment by Irev-Dev** [comment]
Hey @lopisan,
Thanks again for pointing this out, and a well-written bug report.
This should be resolved now, please use the latest version of the code.

Let me know if you have any more issues, or if there's any way I can help you.

Cheers,
Kurt.

**Comment by lopisan** [comment]
Thanks for the fast fix, it is working now.
