### ISSUE TITLE
WARNING: undefined operation (undefined + number) in file polyround.scad, line 174 when using polyRoundExtrude()

### ISSUE THREAD

**Issue by fex42** [Irev-Dev/Round-Anything#22]
Hi Kurt, let me first thank you for this great library that helps me make my humble designs look a little less angular.

Now that I use the polyRoundExtrude() more often, I always get this four warnings that also comes with the polyRoundExtrudeExample() in your roundAnythingExamples.scad:

Loaded design '/home/fex/3D-Druck/OpenSCAD/Round-Anything/roundAnythingExamples.scad'.
Compiling design (CSG Tree generation)...
WARNING: undefined operation (undefined + number) in file polyround.scad, line 174 
WARNING: undefined operation (undefined + number) in file polyround.scad, line 174 
WARNING: undefined operation (undefined + number) in file polyround.scad, line 174 
WARNING: undefined operation (undefined + number) in file polyround.scad, line 174 

The warning is annoying and should not happen. Is there a way to avoid this?

**Comment by damienmg** [comment]
I just hit this issue and was able to fix it on my local copy so I send #23 to fix.

**Comment by Irev-Dev** [comment]
Thanks for raising this @fex42.
