### ISSUE TITLE
polyRoundExtrude can run unboundedly

### ISSUE THREAD

**Issue by Trial-In-Error** [Irev-Dev/Round-Anything#26]
```
use <Round-Anything/polyround.scad>
polyRoundExtrude([], 20, 1, 1);
```

Bad input frequently leaves `polyRoundExtrude` rendering indefinitely. Is this a problem where the rules for valid/invalid input are easy enough to validate? If not, is it possible to put a max on the # of iterations run (possibly as an argument to the method or read from a constant the user can extend)? I'm unsure how to get out of this state besides killing the openSCAD process.

**Comment by Irev-Dev** [comment]
Happy with #28 @Trial-In-Error ?
