### ISSUE TITLE
Attachment Point Conundrum

### ISSUE THREAD

**Issue by RAMilewski** [Irev-Dev/Round-Anything#41]
I suspect there is no easy answer to this, but it's been more than half a century since my last math class and I wanted to check in case I missed something really obvious.

Given the code below is there a way calculate the location of the point on the curve closest to the black dot ( [20,25] ) for various rounding values?

`use <Round-Anything-1.0.4/polyround.scad>

points = [
    [0,  0,   0],
    [10, 0,   0],
    [10, 10, 20],
    [20, 25, 10],
    [0,  15, 20]
];

$fn = 18;
polyline(points, 0.5);  
translate([20,25,0]) color("black") circle(0.5);

translate([20,0,0]) { 
    polyline(polyRound(points), 0.5);
    translate([20,25,0]) color("black") circle(0.5);
}`

![Screen Shot 2022-04-28 at 3 33 51 PM](https://user-images.githubusercontent.com/702294/165859945-cc5e8be8-dd30-402d-81b2-bb082bb6a287.png)

**Comment by Irev-Dev** [comment]
Does this help?
https://github.com/Irev-Dev/Round-Anything/blob/master/images/formulas.png

**Comment by RAMilewski** [comment]
Perfect, Thank you!
